// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/80060c94ef549c077a011977c2b5461bd0fd8947/pdfobject/index.d.ts
declare module "pdfobject" {
    interface PDFObject {
        embed(url:string, target?:any, options?:any): HTMLElement;
        pdfobjectversion: string;
        supportsPDFs: boolean;
    }

    var pdfObject: PDFObject;
    export = pdfObject;

}
